###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author/

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author/id/39
accept: application/json

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author/id/1
accept: application/json

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author/author_id/34

###
POST http://localhost:8080/book_manager_war_exploded/api/v1/author/
content-type: application/json

{
  "first_name": "LEON",
  "last_name": "Maurer"
}

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author/id/a HTTP/1.1
accept: application/json


###
POST http://localhost:8080/book_manager_war_exploded/api/v1/author/
content-type: application/json

{
  "first_name": "Safiye",
  "last_name": "Uzun"
}

###
PUT http://localhost:8080/book_manager_war_exploded/api/v1/author/id/40
content-type: application/json

{
  "first_name": "Michele",
  "last_name": "Obama"
}

###
DELETE http://localhost:8080/book_manager_war_exploded/api/v1/author/id/40

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author
