###
GET http://localhost:8080/book_manager_war_exploded/api/v1/book/

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/book/author/id/39
accept: application/json

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/book/isbn/978-3-15-006172-5
accept: application/json

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author/author_id/34

###
POST http://localhost:8080/book_manager_war_exploded/api/v1/book/
content-type: application/json

{
  "first_name": "Safiye",
  "last_name": "Uzun",
  "title": "Java",
  "isbn": "111-222-333",
  "publisher": "goldmann",
  "year": "2018"
}

###
POST http://localhost:8080/book_manager_war_exploded/api/v1/author/
content-type: application/json

{
  "first_name": "Michelle",
  "last_name": "Obama"
}

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author/id/a HTTP/1.1
accept: application/json


###
POST http://localhost:8080/book_manager_war_exploded/api/v1/author/
content-type: application/json

{
  "first_name": "Safiye",
  "last_name": "Uzun"
}

###
PUT http://localhost:8080/book_manager_war_exploded/api/v1/author/id/40
content-type: application/json

{
  "first_name": "Peter",
  "last_name": "Robisch"
}

###
DELETE http://localhost:8080/book_manager_war_exploded/api/v1/author/id/34

###
GET http://localhost:8080/book_manager_war_exploded/api/v1/author


